spring.application.name=orders-service


# Ensure global configuration properties are fetched from Config Server
#spring.cloud.config.name=orders-service
#spring.cloud.config.uri=http://localhost:8888/

spring.cloud.discovery.enabled=true
spring.config.import=configserver:http://localhost:8888
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
spring.cloud.config.uri=http://localhost:8888

#spring.cloud.discovery.enabled=true
server.port=8081
