spring.application.name=orders-service

spring.config.import=configserver:http://localhost:8888/
# Ensure global configuration properties are fetched from Config Server
spring.cloud.config.name=orders-service

spring.cloud.discovery.enabled=true
server.port=8081