spring.application.name=orders-service

spring.datasource.url=jdbc:mysql://127.0.0.1:3307/orders_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Ensure global configuration properties are fetched from Config Server
spring.cloud.config.uri=http://localhost:8888
spring.cloud.config.name=orders-service

spring.cloud.discovery.enabled=true
server.port=8081