spring.application.name=config-server

server.port=8888

spring.cloud.config.server.git.uri=https://github.com/ZakariaeNaaim/micro-services
spring.cloud.config.server.git.search-paths=aura-snack-api/config
spring.cloud.config.server.git.clone-on-start=true

