spring.application.name=gateway

server.port=8080

# Configuration Server URL (assuming it's running on localhost:8888)
spring.cloud.config.uri=http://localhost:8888

# Optional: Default profile
spring.profiles.active=dev

