logging.level.root=INFO
spring.profiles.active=dev

# Enable basic authentication
spring.security.user.name=user
spring.security.user.password=$2a$12$iICQjFNopbxOBCg2ylhiSeA1Z5mIwNRN8jOsG4Yw0FolbR5ywt6M2
