logging.level.root=INFO
spring.profiles.active=default

# Enable basic authentication
spring.security.user.name=user
spring.security.user.password=$2a$12$iICQjFNopbxOBCg2ylhiSeA1Z5mIwNRN8jOsG4Yw0FolbR5ywt6M2


spring.datasource.url=jdbc:mysql://127.0.0.1:3307/aura_snack_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

eureka.instance.prefer-ip-address=true
eureka.client.service-url.default-zone=${EUREKA_URI:http://localhost:8761/eureka}

application-version=1.0