spring.application.name=inventory-service

# Ensure global configuration properties are fetched from Config Server
spring.cloud.config.uri=http://localhost:8888
spring.cloud.config.name=inventory-service



spring.cloud.discovery.enabled=true
server.port=8082

spring.config.import=configserver:http://localhost:8888
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/